{% set name = "latte-integrale" %}
{% set version = "1.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/latte-int/latte/releases/download/version_{{ version | replace('.', '_') }}/latte-int-{{ version }}.tar.gz
  sha256: 006c10ebe5d5bfdc9b159cba6264a4432861fe763ce05fe821624ab7d3fc2170

build:
  number: 1
  skip: True  # [win]
  run_exports:
    # LattE integrale provides a liblatte library which is not very widely used.
    # Nevertheless it should automatically appear in run when used in host.
    - {{ pin_subpackage("latte-integrale") }}

requirements:
  build:
    - automake
    - make
    - libtool
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - perl
  host:
    - ntl
    - gmp
    - cddlib
    - 4ti2
  run:
    - 4ti2

test:
  source_files:
    - EXAMPLES/24_cell
    - EXAMPLES/24_cell.cost
  commands:
    - count EXAMPLES/24_cell
    - integrate EXAMPLES/24_cell --valuation=volume
    - latte-minimize EXAMPLES/24_cell
    - latte-maximize EXAMPLES/24_cell

about:
  home: https://www.math.ucdavis.edu/~latte/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'software for counting lattice points and integration over convex polytopes'
  description: |
    This is LattE integrale, the official new version of LattE.
    In addition to the traditional LattE function of counting lattice
    points in polytopes by variants of Barvinok's algorithm, LattE
    integrale can also compute volumes and integrate polynomial functions
    over polytopes.  It supersedes LattE macchiato, an improved version of 
    LattE.
  doc_url: https://github.com/latte-int/latte/blob/master/doc/manual.pdf
  dev_url: https://github.com/latte-int/latte

extra:
  recipe-maintainers:
    - saraedum
