travis:
  secure:
    BINSTAR_TOKEN: b/YtRSlNcAUSJrI3ifkI2Fp3W8H2GU7FHD1E61k39vQHA/e0zq718ZrMiJjPZw/mwUdDUikPyApY45KwHZCCj4ITcG9ksq3RTShDkurM8n4hFJZCcAh3/pNnDBmXiyI7l+1arZSp+w4mj9JJriaxfE3C5KYrHxmGbToy4nI03p73V3P5V7FcpX5bDyKYIjf39kZd5OwryRRri4m/8cGrcCZXU8hA3IUM9Rg/QVxswRLt2IQ1ezRF2NGZJ+0ZVYTh5D/75Qm7i5RGipToICUvpb3fjraLLchXf6A9xSWEkVi3lygvwkEXZDLoQ4wvOVMB8nDzWyMX/pdREtkhjiFzl3guA0FWzy90TK3IKmY8EB7hvjuMLigc0iyUQ6X/t2ZkUuiTD3Nc0XLiJvIt24FTFH3BcNWrpdPbRr4+JafcN6OTQ6t/pnUK9qlIZlvO/HnO9lZIZ3veMK2NW3VSRCB3TyRWVrnLi1nhRmPFm+jUfiw6ZfbfCUjkLJKQVd2ByAxLWTk5aU6aYsDOQ26SdQh3B3DCKUZA6wcsNZsBuYUDS2oBrtQWddxnO8XcXQ5o/hgAcS+WQRRLGuSRBBURFkN6HpxK4PR7PlCqcN08e+SQZv/ouh17W8cAB/36NRD6rdQtuH6O7C42mO8Zbo94fGOxV+dqtCoFDLgmjzwhwVYWOEo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
